# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.LearningRateMonitor.html

early_stopping:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: "step"
